// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

// 一周的7天
type SchedulerWeekday string

const (
	SchedulerWeekday1 SchedulerWeekday = "1"
	SchedulerWeekday2 SchedulerWeekday = "2"
	SchedulerWeekday3 SchedulerWeekday = "3"
	SchedulerWeekday4 SchedulerWeekday = "4"
	SchedulerWeekday5 SchedulerWeekday = "5"
	SchedulerWeekday6 SchedulerWeekday = "6"
	SchedulerWeekday7 SchedulerWeekday = "7"
)

func (e *SchedulerWeekday) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SchedulerWeekday(s)
	case string:
		*e = SchedulerWeekday(s)
	default:
		return fmt.Errorf("unsupported scan type for SchedulerWeekday: %T", src)
	}
	return nil
}

type NullSchedulerWeekday struct {
	SchedulerWeekday SchedulerWeekday `json:"scheduler_weekday"`
	Valid            bool             `json:"valid"` // Valid is true if SchedulerWeekday is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSchedulerWeekday) Scan(value interface{}) error {
	if value == nil {
		ns.SchedulerWeekday, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SchedulerWeekday.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSchedulerWeekday) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SchedulerWeekday), nil
}

type WtsAccess string

const (
	WtsAccessDev            WtsAccess = "dev"
	WtsAccessChief          WtsAccess = "chief"
	WtsAccessApi            WtsAccess = "api"
	WtsAccessGroupLeader    WtsAccess = "group-leader"
	WtsAccessFormalMember   WtsAccess = "formal-member"
	WtsAccessInformalMember WtsAccess = "informal-member"
	WtsAccessPreMember      WtsAccess = "pre-member"
	WtsAccessUser           WtsAccess = "user"
	WtsAccessUnregistered   WtsAccess = "unregistered"
)

func (e *WtsAccess) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = WtsAccess(s)
	case string:
		*e = WtsAccess(s)
	default:
		return fmt.Errorf("unsupported scan type for WtsAccess: %T", src)
	}
	return nil
}

type NullWtsAccess struct {
	WtsAccess WtsAccess `json:"wts_access"`
	Valid     bool      `json:"valid"` // Valid is true if WtsAccess is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullWtsAccess) Scan(value interface{}) error {
	if value == nil {
		ns.WtsAccess, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.WtsAccess.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullWtsAccess) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.WtsAccess), nil
}

// 宿舍的楼号
type WtsBlock string

const (
	WtsBlock1     WtsBlock = "1"
	WtsBlock2     WtsBlock = "2"
	WtsBlock3     WtsBlock = "3"
	WtsBlock4     WtsBlock = "4"
	WtsBlock5     WtsBlock = "5"
	WtsBlock6     WtsBlock = "6"
	WtsBlock7     WtsBlock = "7"
	WtsBlock8     WtsBlock = "8"
	WtsBlock9     WtsBlock = "9"
	WtsBlock10    WtsBlock = "10"
	WtsBlock11    WtsBlock = "11"
	WtsBlock12    WtsBlock = "12"
	WtsBlock13    WtsBlock = "13"
	WtsBlock14    WtsBlock = "14"
	WtsBlock15    WtsBlock = "15"
	WtsBlock16    WtsBlock = "16"
	WtsBlock17    WtsBlock = "17"
	WtsBlock18    WtsBlock = "18"
	WtsBlock19    WtsBlock = "19"
	WtsBlock20    WtsBlock = "20"
	WtsBlock21    WtsBlock = "21"
	WtsBlock22    WtsBlock = "22"
	WtsBlockXHA   WtsBlock = "XHA"
	WtsBlockXHB   WtsBlock = "XHB"
	WtsBlockXHC   WtsBlock = "XHC"
	WtsBlockXHD   WtsBlock = "XHD"
	WtsBlockZH    WtsBlock = "ZH"
	WtsBlockOther WtsBlock = "other"
)

func (e *WtsBlock) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = WtsBlock(s)
	case string:
		*e = WtsBlock(s)
	default:
		return fmt.Errorf("unsupported scan type for WtsBlock: %T", src)
	}
	return nil
}

type NullWtsBlock struct {
	WtsBlock WtsBlock `json:"wts_block"`
	Valid    bool     `json:"valid"` // Valid is true if WtsBlock is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullWtsBlock) Scan(value interface{}) error {
	if value == nil {
		ns.WtsBlock, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.WtsBlock.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullWtsBlock) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.WtsBlock), nil
}

// 故障的类型
type WtsCategory string

const (
	WtsCategoryFirstInstall    WtsCategory = "first-install"
	WtsCategoryLowSpeed        WtsCategory = "low-speed"
	WtsCategoryIpOrDevice      WtsCategory = "ip-or-device"
	WtsCategoryClientOrAccount WtsCategory = "client-or-account"
	WtsCategoryOthers          WtsCategory = "others"
)

func (e *WtsCategory) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = WtsCategory(s)
	case string:
		*e = WtsCategory(s)
	default:
		return fmt.Errorf("unsupported scan type for WtsCategory: %T", src)
	}
	return nil
}

type NullWtsCategory struct {
	WtsCategory WtsCategory `json:"wts_category"`
	Valid       bool        `json:"valid"` // Valid is true if WtsCategory is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullWtsCategory) Scan(value interface{}) error {
	if value == nil {
		ns.WtsCategory, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.WtsCategory.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullWtsCategory) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.WtsCategory), nil
}

// 运营商
type WtsIsp string

const (
	WtsIspTelecom  WtsIsp = "telecom"
	WtsIspUnicom   WtsIsp = "unicom"
	WtsIspMobile   WtsIsp = "mobile"
	WtsIspOthers   WtsIsp = "others"
	WtsIspBroadnet WtsIsp = "broadnet"
)

func (e *WtsIsp) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = WtsIsp(s)
	case string:
		*e = WtsIsp(s)
	default:
		return fmt.Errorf("unsupported scan type for WtsIsp: %T", src)
	}
	return nil
}

type NullWtsIsp struct {
	WtsIsp WtsIsp `json:"wts_isp"`
	Valid  bool   `json:"valid"` // Valid is true if WtsIsp is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullWtsIsp) Scan(value interface{}) error {
	if value == nil {
		ns.WtsIsp, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.WtsIsp.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullWtsIsp) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.WtsIsp), nil
}

// 工单的优先级
type WtsPriority string

const (
	WtsPriorityHighest   WtsPriority = "highest"
	WtsPriorityAssigned  WtsPriority = "assigned"
	WtsPriorityMainline  WtsPriority = "mainline"
	WtsPriorityNormal    WtsPriority = "normal"
	WtsPriorityInPassing WtsPriority = "in-passing"
	WtsPriorityLeast     WtsPriority = "least"
)

func (e *WtsPriority) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = WtsPriority(s)
	case string:
		*e = WtsPriority(s)
	default:
		return fmt.Errorf("unsupported scan type for WtsPriority: %T", src)
	}
	return nil
}

type NullWtsPriority struct {
	WtsPriority WtsPriority `json:"wts_priority"`
	Valid       bool        `json:"valid"` // Valid is true if WtsPriority is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullWtsPriority) Scan(value interface{}) error {
	if value == nil {
		ns.WtsPriority, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.WtsPriority.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullWtsPriority) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.WtsPriority), nil
}

// 工单的状态
type WtsStatus string

const (
	WtsStatusFresh     WtsStatus = "fresh"
	WtsStatusScheduled WtsStatus = "scheduled"
	WtsStatusDelay     WtsStatus = "delay"
	WtsStatusEscalated WtsStatus = "escalated"
	WtsStatusSolved    WtsStatus = "solved"
	WtsStatusCanceled  WtsStatus = "canceled"
)

func (e *WtsStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = WtsStatus(s)
	case string:
		*e = WtsStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for WtsStatus: %T", src)
	}
	return nil
}

type NullWtsStatus struct {
	WtsStatus WtsStatus `json:"wts_status"`
	Valid     bool      `json:"valid"` // Valid is true if WtsStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullWtsStatus) Scan(value interface{}) error {
	if value == nil {
		ns.WtsStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.WtsStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullWtsStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.WtsStatus), nil
}

// 学校所有学生的姓名和学号，系统依赖于这个表运行，记录由管理人员负责插入
type DataStudent struct {
	// 学号
	Sid string `json:"sid"`
	// 姓名
	Name string `json:"name"`
}

// 每个成员在哪天有空的记录
type SchedulerFreeday struct {
	// 工号
	Wid string `json:"wid"`
	// 在哪天有空
	FreeAt SchedulerWeekday `json:"free_at"`
}

// 网维的成员
type WtsOperator struct {
	// 工号
	Wid string `json:"wid"`
	// 学号
	Sid string `json:"sid"`
	// 权限
	Access WtsAccess `json:"access"`
	// 是不是女生
	Female bool `json:"female"`
}

// 工单
type WtsTicket struct {
	// 工单的编号，自增主键
	Tid int32 `json:"tid"`
	// 报修人（学号）
	Issuer string `json:"issuer"`
	// 工单提交时间
	SubmittedAt pgtype.Timestamptz `json:"submitted_at"`
	// 故障的类型
	Category WtsCategory `json:"category"`
	// 错误描述，用户所填的..
	Description string `json:"description"`
	// 网络故障的出现时间（大概）
	OccurAt pgtype.Timestamptz `json:"occur_at"`
	// 备注，用户所填的
	Notes pgtype.Text `json:"notes"`
	// 预约上门的日期，冗余
	AppointedAt pgtype.Date `json:"appointed_at"`
	// 优先级,冗余
	Priority WtsPriority `json:"priority"`
	// 工单目前的状态,冗余
	Status WtsStatus `json:"status"`
	// 工单最后更新的时间，冗余
	LastUpdatedAt pgtype.Timestamptz `json:"last_updated_at"`
}

// 工单的情况追踪
type WtsTicketTrace struct {
	// 一个操作的编号，自增主键。
	Opid int32 `json:"opid"`
	// 工单的编号
	Tid int32 `json:"tid"`
	// 该追踪更新的日期
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	// 进行操作的网维成员
	Op string `json:"op"`
	// 工单的新状态(若有)，没有则NULL
	NewStatus NullWtsStatus `json:"new_status"`
	// 工单的新优先级，没有则NULL
	NewPriority NullWtsPriority `json:"new_priority"`
	// 新的预约时间
	NewAppointment pgtype.Date `json:"new_appointment"`
	// 工单的新类型，没有则NULL
	NewCategory NullWtsCategory `json:"new_category"`
	// 本次修改的说明
	Remark string `json:"remark"`
}

// 报修系统的用户
type WtsUser struct {
	// 用户的学号
	Sid string `json:"sid"`
	// 用于联系用户的手机号
	Phone pgtype.Text `json:"phone"`
	// 楼号
	Block NullWtsBlock `json:"block"`
	// 房间
	Room pgtype.Text `json:"room"`
	// 运营商
	Isp NullWtsIsp `json:"isp"`
	// 宽带的账号
	Account pgtype.Text `json:"account"`
	// 微信(OpenID)
	Wx string `json:"wx"`
	// 是不是网维
	Op bool `json:"op"`
	// 注册的时间
	RegisteredAt pgtype.Timestamptz `json:"registered_at"`
	// 最近个人信息更新的时间
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

// 活跃的工单
type WtsVActiveTicket struct {
	Tid           int32              `json:"tid"`
	Issuer        string             `json:"issuer"`
	SubmittedAt   pgtype.Timestamptz `json:"submitted_at"`
	Category      WtsCategory        `json:"category"`
	Description   string             `json:"description"`
	OccurAt       pgtype.Timestamptz `json:"occur_at"`
	Notes         pgtype.Text        `json:"notes"`
	AppointedAt   pgtype.Date        `json:"appointed_at"`
	Priority      WtsPriority        `json:"priority"`
	Status        WtsStatus          `json:"status"`
	LastUpdatedAt pgtype.Timestamptz `json:"last_updated_at"`
	Name          pgtype.Text        `json:"name"`
	Block         NullWtsBlock       `json:"block"`
	Room          pgtype.Text        `json:"room"`
	Isp           NullWtsIsp         `json:"isp"`
	Account       pgtype.Text        `json:"account"`
	Phone         pgtype.Text        `json:"phone"`
}

// 网维的成员
type WtsVOperator struct {
	Wid    string      `json:"wid"`
	Name   pgtype.Text `json:"name"`
	Access WtsAccess   `json:"access"`
	Female bool        `json:"female"`
}

// 工单的视图
type WtsVTicket struct {
	Tid           int32              `json:"tid"`
	Issuer        string             `json:"issuer"`
	SubmittedAt   pgtype.Timestamptz `json:"submitted_at"`
	Category      WtsCategory        `json:"category"`
	Description   string             `json:"description"`
	OccurAt       pgtype.Timestamptz `json:"occur_at"`
	Notes         pgtype.Text        `json:"notes"`
	AppointedAt   pgtype.Date        `json:"appointed_at"`
	Priority      WtsPriority        `json:"priority"`
	Status        WtsStatus          `json:"status"`
	LastUpdatedAt pgtype.Timestamptz `json:"last_updated_at"`
	Name          pgtype.Text        `json:"name"`
	Block         NullWtsBlock       `json:"block"`
	Room          pgtype.Text        `json:"room"`
	Isp           NullWtsIsp         `json:"isp"`
	Account       pgtype.Text        `json:"account"`
	Phone         pgtype.Text        `json:"phone"`
}

type WtsVUser struct {
	Sid     pgtype.Text   `json:"sid"`
	Name    pgtype.Text   `json:"name"`
	Phone   pgtype.Text   `json:"phone"`
	Block   NullWtsBlock  `json:"block"`
	Room    pgtype.Text   `json:"room"`
	Isp     NullWtsIsp    `json:"isp"`
	Account pgtype.Text   `json:"account"`
	Op      bool          `json:"op"`
	Wx      string        `json:"wx"`
	Access  NullWtsAccess `json:"access"`
}
