// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTicket = `-- name: CreateTicket :one

INSERT INTO wts.tickets (
  issuer, submitted_at, occur_at, description, appointed_at, notes, priority, category, status
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9
)
RETURNING tid, issuer, submitted_at, category, description, occur_at, notes, appointed_at, priority, status, last_updated_at
`

type CreateTicketParams struct {
	Issuer      string             `json:"issuer"`
	SubmittedAt pgtype.Timestamptz `json:"submitted_at"`
	OccurAt     pgtype.Timestamptz `json:"occur_at"`
	Description string             `json:"description"`
	AppointedAt pgtype.Date        `json:"appointed_at"`
	Notes       pgtype.Text        `json:"notes"`
	Priority    WtsPriority        `json:"priority"`
	Category    WtsCategory        `json:"category"`
	Status      WtsStatus          `json:"status"`
}

// 工单管理--
func (q *Queries) CreateTicket(ctx context.Context, arg CreateTicketParams) (WtsTicket, error) {
	row := q.db.QueryRow(ctx, createTicket,
		arg.Issuer,
		arg.SubmittedAt,
		arg.OccurAt,
		arg.Description,
		arg.AppointedAt,
		arg.Notes,
		arg.Priority,
		arg.Category,
		arg.Status,
	)
	var i WtsTicket
	err := row.Scan(
		&i.Tid,
		&i.Issuer,
		&i.SubmittedAt,
		&i.Category,
		&i.Description,
		&i.OccurAt,
		&i.Notes,
		&i.AppointedAt,
		&i.Priority,
		&i.Status,
		&i.LastUpdatedAt,
	)
	return i, err
}

const createTicketTrace = `-- name: CreateTicketTrace :one

INSERT INTO wts.ticket_traces (
  tid, updated_at, op, new_status, new_priority, new_appointment, new_category, remark
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING opid, tid, updated_at, op, new_status, new_priority, new_appointment, new_category, remark
`

type CreateTicketTraceParams struct {
	Tid            int32              `json:"tid"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	Op             string             `json:"op"`
	NewStatus      NullWtsStatus      `json:"new_status"`
	NewPriority    NullWtsPriority    `json:"new_priority"`
	NewAppointment pgtype.Date        `json:"new_appointment"`
	NewCategory    NullWtsCategory    `json:"new_category"`
	Remark         string             `json:"remark"`
}

// traces管理 --
func (q *Queries) CreateTicketTrace(ctx context.Context, arg CreateTicketTraceParams) (WtsTicketTrace, error) {
	row := q.db.QueryRow(ctx, createTicketTrace,
		arg.Tid,
		arg.UpdatedAt,
		arg.Op,
		arg.NewStatus,
		arg.NewPriority,
		arg.NewAppointment,
		arg.NewCategory,
		arg.Remark,
	)
	var i WtsTicketTrace
	err := row.Scan(
		&i.Opid,
		&i.Tid,
		&i.UpdatedAt,
		&i.Op,
		&i.NewStatus,
		&i.NewPriority,
		&i.NewAppointment,
		&i.NewCategory,
		&i.Remark,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO wts.users (
  sid, phone, block, room, isp, account, wx
) VALUES (
  $1, $2, $3, $4, $5, $6, $7
)
RETURNING sid, phone, block, room, isp, account, wx, op, registered_at, updated_at
`

type CreateUserParams struct {
	Sid     string       `json:"sid"`
	Phone   pgtype.Text  `json:"phone"`
	Block   NullWtsBlock `json:"block"`
	Room    pgtype.Text  `json:"room"`
	Isp     NullWtsIsp   `json:"isp"`
	Account pgtype.Text  `json:"account"`
	Wx      string       `json:"wx"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (WtsUser, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Sid,
		arg.Phone,
		arg.Block,
		arg.Room,
		arg.Isp,
		arg.Account,
		arg.Wx,
	)
	var i WtsUser
	err := row.Scan(
		&i.Sid,
		&i.Phone,
		&i.Block,
		&i.Room,
		&i.Isp,
		&i.Account,
		&i.Wx,
		&i.Op,
		&i.RegisteredAt,
		&i.UpdatedAt,
	)
	return i, err
}

const filterActiveTickets = `-- name: FilterActiveTickets :many
SELECT tid, issuer, submitted_at, category, description, occur_at, notes, appointed_at, priority, status, last_updated_at, name, block, room, isp, account, phone
FROM wts.v_active_tickets t
WHERE 
    ($1::wts.block[] IS NULL OR t.block = ANY($1::wts.block[]))
AND t.issuer = COALESCE($2, t.issuer)
AND ($3::wts.category[] IS NULL OR t.category = ANY($3::wts.category[]))
AND ($4::wts.isp[] IS NULL OR t.isp = ANY($4::wts.isp[]))
AND t.submitted_at >= COALESCE($5, '1970-01-01'::timestamptz)
AND t.submitted_at <= COALESCE($6, NOW()::timestamptz)
AND ($7::wts.status[] IS NULL OR t.status = ANY($7::wts.status[]))
ORDER BY t.priority ASC
`

type FilterActiveTicketsParams struct {
	Blocks    []WtsBlock         `json:"blocks"`
	Issuer    pgtype.Text        `json:"issuer"`
	Category  []WtsCategory      `json:"category"`
	Isp       []WtsIsp           `json:"isp"`
	NewerThan pgtype.Timestamptz `json:"newerThan"`
	OlderThan pgtype.Timestamptz `json:"olderThan"`
	Status    []WtsStatus        `json:"status"`
}

func (q *Queries) FilterActiveTickets(ctx context.Context, arg FilterActiveTicketsParams) ([]WtsVActiveTicket, error) {
	rows, err := q.db.Query(ctx, filterActiveTickets,
		arg.Blocks,
		arg.Issuer,
		arg.Category,
		arg.Isp,
		arg.NewerThan,
		arg.OlderThan,
		arg.Status,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WtsVActiveTicket
	for rows.Next() {
		var i WtsVActiveTicket
		if err := rows.Scan(
			&i.Tid,
			&i.Issuer,
			&i.SubmittedAt,
			&i.Category,
			&i.Description,
			&i.OccurAt,
			&i.Notes,
			&i.AppointedAt,
			&i.Priority,
			&i.Status,
			&i.LastUpdatedAt,
			&i.Name,
			&i.Block,
			&i.Room,
			&i.Isp,
			&i.Account,
			&i.Phone,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const filterTickets = `-- name: FilterTickets :many
SELECT tid, issuer, submitted_at, category, description, occur_at, notes, appointed_at, priority, status, last_updated_at, name, block, room, isp, account, phone
FROM wts.v_tickets t
WHERE 
    ($1::wts.block[] IS NULL OR t.block = ANY($1::wts.block[]))
AND t.issuer = COALESCE($2, t.issuer)
AND ($3::wts.category[] IS NULL OR t.category = ANY($3::wts.category[]))
AND ($4::wts.isp[] IS NULL OR t.isp = ANY($4::wts.isp[]))
AND t.submitted_at >= COALESCE($5, '1970-01-01'::timestamptz)
AND t.submitted_at <= COALESCE($6, NOW()::timestamptz)
AND ($7::wts.status[] IS NULL OR t.status = ANY($7::wts.status[]))
ORDER BY t.priority ASC
`

type FilterTicketsParams struct {
	Blocks    []WtsBlock         `json:"blocks"`
	Issuer    pgtype.Text        `json:"issuer"`
	Category  []WtsCategory      `json:"category"`
	Isp       []WtsIsp           `json:"isp"`
	NewerThan pgtype.Timestamptz `json:"newerThan"`
	OlderThan pgtype.Timestamptz `json:"olderThan"`
	Status    []WtsStatus        `json:"status"`
}

func (q *Queries) FilterTickets(ctx context.Context, arg FilterTicketsParams) ([]WtsVTicket, error) {
	rows, err := q.db.Query(ctx, filterTickets,
		arg.Blocks,
		arg.Issuer,
		arg.Category,
		arg.Isp,
		arg.NewerThan,
		arg.OlderThan,
		arg.Status,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WtsVTicket
	for rows.Next() {
		var i WtsVTicket
		if err := rows.Scan(
			&i.Tid,
			&i.Issuer,
			&i.SubmittedAt,
			&i.Category,
			&i.Description,
			&i.OccurAt,
			&i.Notes,
			&i.AppointedAt,
			&i.Priority,
			&i.Status,
			&i.LastUpdatedAt,
			&i.Name,
			&i.Block,
			&i.Room,
			&i.Isp,
			&i.Account,
			&i.Phone,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const filterUsers = `-- name: FilterUsers :many
SELECT sid, name, phone, block, room, isp, account, op, wx, access
FROM wts.v_users u
WHERE 
    u.name LIKE COALESCE($1, '%')
AND u.phone = COALESCE($2, u.phone)
AND u.block = COALESCE($3, u.block)
AND u.room = COALESCE($4, u.room)
AND u.isp = COALESCE($5, u.isp)
AND u.account = COALESCE($6, u.account)
ORDER BY u.sid
`

type FilterUsersParams struct {
	Name    pgtype.Text  `json:"name"`
	Phone   pgtype.Text  `json:"phone"`
	Block   NullWtsBlock `json:"block"`
	Room    pgtype.Text  `json:"room"`
	Isp     NullWtsIsp   `json:"isp"`
	Account pgtype.Text  `json:"account"`
}

func (q *Queries) FilterUsers(ctx context.Context, arg FilterUsersParams) ([]WtsVUser, error) {
	rows, err := q.db.Query(ctx, filterUsers,
		arg.Name,
		arg.Phone,
		arg.Block,
		arg.Room,
		arg.Isp,
		arg.Account,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WtsVUser
	for rows.Next() {
		var i WtsVUser
		if err := rows.Scan(
			&i.Sid,
			&i.Name,
			&i.Phone,
			&i.Block,
			&i.Room,
			&i.Isp,
			&i.Account,
			&i.Op,
			&i.Wx,
			&i.Access,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getActiveTicketCountByBlock = `-- name: GetActiveTicketCountByBlock :many

SELECT block, COUNT(*) AS total
FROM wts.v_active_tickets
WHERE block IS NOT NULL
GROUP BY block
ORDER BY total DESC
`

type GetActiveTicketCountByBlockRow struct {
	Block NullWtsBlock `json:"block"`
	Total int64        `json:"total"`
}

// 数据分析--
func (q *Queries) GetActiveTicketCountByBlock(ctx context.Context) ([]GetActiveTicketCountByBlockRow, error) {
	rows, err := q.db.Query(ctx, getActiveTicketCountByBlock)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetActiveTicketCountByBlockRow
	for rows.Next() {
		var i GetActiveTicketCountByBlockRow
		if err := rows.Scan(&i.Block, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getNameBySID = `-- name: GetNameBySID :one




SELECT name FROM data.students
WHERE sid = $1
LIMIT 1
`

// 注意，这里的SQL查询就基本相当于数据库的API，非必要不改动，除非你想大量重构已有的代码 --
// 用户管理--
func (q *Queries) GetNameBySID(ctx context.Context, sid string) (string, error) {
	row := q.db.QueryRow(ctx, getNameBySID, sid)
	var name string
	err := row.Scan(&name)
	return name, err
}

const getStaffBySid = `-- name: GetStaffBySid :one
SELECT wid, sid, access, female FROM wts.operators
WHERE sid = $1
LIMIT 1
`

func (q *Queries) GetStaffBySid(ctx context.Context, sid string) (WtsOperator, error) {
	row := q.db.QueryRow(ctx, getStaffBySid, sid)
	var i WtsOperator
	err := row.Scan(
		&i.Wid,
		&i.Sid,
		&i.Access,
		&i.Female,
	)
	return i, err
}

const getStaffByWid = `-- name: GetStaffByWid :one

SELECT wid, sid, access, female FROM wts.operators
WHERE wid = $1
LIMIT 1
`

// 网维成员管理--
func (q *Queries) GetStaffByWid(ctx context.Context, wid string) (WtsOperator, error) {
	row := q.db.QueryRow(ctx, getStaffByWid, wid)
	var i WtsOperator
	err := row.Scan(
		&i.Wid,
		&i.Sid,
		&i.Access,
		&i.Female,
	)
	return i, err
}

const getTicket = `-- name: GetTicket :one
SELECT tid, issuer, submitted_at, category, description, occur_at, notes, appointed_at, priority, status, last_updated_at, name, block, room, isp, account, phone FROM wts.v_tickets
WHERE tid = $1 LIMIT 1
`

func (q *Queries) GetTicket(ctx context.Context, tid int32) (WtsVTicket, error) {
	row := q.db.QueryRow(ctx, getTicket, tid)
	var i WtsVTicket
	err := row.Scan(
		&i.Tid,
		&i.Issuer,
		&i.SubmittedAt,
		&i.Category,
		&i.Description,
		&i.OccurAt,
		&i.Notes,
		&i.AppointedAt,
		&i.Priority,
		&i.Status,
		&i.LastUpdatedAt,
		&i.Name,
		&i.Block,
		&i.Room,
		&i.Isp,
		&i.Account,
		&i.Phone,
	)
	return i, err
}

const getUserBySID = `-- name: GetUserBySID :one
SELECT sid, name, phone, block, room, isp, account, op, wx, access FROM wts.v_users
WHERE sid = $1
LIMIT 1
`

func (q *Queries) GetUserBySID(ctx context.Context, sid pgtype.Text) (WtsVUser, error) {
	row := q.db.QueryRow(ctx, getUserBySID, sid)
	var i WtsVUser
	err := row.Scan(
		&i.Sid,
		&i.Name,
		&i.Phone,
		&i.Block,
		&i.Room,
		&i.Isp,
		&i.Account,
		&i.Op,
		&i.Wx,
		&i.Access,
	)
	return i, err
}

const getUserByWX = `-- name: GetUserByWX :one
SELECT sid, name, phone, block, room, isp, account, op, wx, access FROM wts.v_users
WHERE wx = $1
LIMIT 1
`

func (q *Queries) GetUserByWX(ctx context.Context, wx string) (WtsVUser, error) {
	row := q.db.QueryRow(ctx, getUserByWX, wx)
	var i WtsVUser
	err := row.Scan(
		&i.Sid,
		&i.Name,
		&i.Phone,
		&i.Block,
		&i.Room,
		&i.Isp,
		&i.Account,
		&i.Op,
		&i.Wx,
		&i.Access,
	)
	return i, err
}

const listActiveTickets = `-- name: ListActiveTickets :many
SELECT tid, issuer, submitted_at, category, description, occur_at, notes, appointed_at, priority, status, last_updated_at, name, block, room, isp, account, phone FROM wts.v_active_tickets
ORDER BY priority DESC, submitted_at DESC
`

func (q *Queries) ListActiveTickets(ctx context.Context) ([]WtsVActiveTicket, error) {
	rows, err := q.db.Query(ctx, listActiveTickets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WtsVActiveTicket
	for rows.Next() {
		var i WtsVActiveTicket
		if err := rows.Scan(
			&i.Tid,
			&i.Issuer,
			&i.SubmittedAt,
			&i.Category,
			&i.Description,
			&i.OccurAt,
			&i.Notes,
			&i.AppointedAt,
			&i.Priority,
			&i.Status,
			&i.LastUpdatedAt,
			&i.Name,
			&i.Block,
			&i.Room,
			&i.Isp,
			&i.Account,
			&i.Phone,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveTicketsByBlocks = `-- name: ListActiveTicketsByBlocks :many

SELECT tid, issuer, submitted_at, category, description, occur_at, notes, appointed_at, priority, status, last_updated_at, name, block, room, isp, account, phone FROM wts.v_active_tickets
WHERE block = ANY($1::wts.block[])
ORDER BY priority DESC, submitted_at DESC
`

// 先按优先级，相同的话再按提交时间
func (q *Queries) ListActiveTicketsByBlocks(ctx context.Context, blocks []WtsBlock) ([]WtsVActiveTicket, error) {
	rows, err := q.db.Query(ctx, listActiveTicketsByBlocks, blocks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WtsVActiveTicket
	for rows.Next() {
		var i WtsVActiveTicket
		if err := rows.Scan(
			&i.Tid,
			&i.Issuer,
			&i.SubmittedAt,
			&i.Category,
			&i.Description,
			&i.OccurAt,
			&i.Notes,
			&i.AppointedAt,
			&i.Priority,
			&i.Status,
			&i.LastUpdatedAt,
			&i.Name,
			&i.Block,
			&i.Room,
			&i.Isp,
			&i.Account,
			&i.Phone,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTicketsByIssuer = `-- name: ListTicketsByIssuer :many
SELECT tid, issuer, submitted_at, category, description, occur_at, notes, appointed_at, priority, status, last_updated_at, name, block, room, isp, account, phone FROM wts.v_tickets
WHERE issuer = $1
ORDER BY submitted_at DESC
`

func (q *Queries) ListTicketsByIssuer(ctx context.Context, issuer string) ([]WtsVTicket, error) {
	rows, err := q.db.Query(ctx, listTicketsByIssuer, issuer)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WtsVTicket
	for rows.Next() {
		var i WtsVTicket
		if err := rows.Scan(
			&i.Tid,
			&i.Issuer,
			&i.SubmittedAt,
			&i.Category,
			&i.Description,
			&i.OccurAt,
			&i.Notes,
			&i.AppointedAt,
			&i.Priority,
			&i.Status,
			&i.LastUpdatedAt,
			&i.Name,
			&i.Block,
			&i.Room,
			&i.Isp,
			&i.Account,
			&i.Phone,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTicketsByStatus = `-- name: ListTicketsByStatus :many
SELECT tid, issuer, submitted_at, category, description, occur_at, notes, appointed_at, priority, status, last_updated_at, name, block, room, isp, account, phone FROM wts.v_tickets
WHERE status = $1
ORDER BY submitted_at DESC
`

func (q *Queries) ListTicketsByStatus(ctx context.Context, status WtsStatus) ([]WtsVTicket, error) {
	rows, err := q.db.Query(ctx, listTicketsByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WtsVTicket
	for rows.Next() {
		var i WtsVTicket
		if err := rows.Scan(
			&i.Tid,
			&i.Issuer,
			&i.SubmittedAt,
			&i.Category,
			&i.Description,
			&i.OccurAt,
			&i.Notes,
			&i.AppointedAt,
			&i.Priority,
			&i.Status,
			&i.LastUpdatedAt,
			&i.Name,
			&i.Block,
			&i.Room,
			&i.Isp,
			&i.Account,
			&i.Phone,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTracesByTicket = `-- name: ListTracesByTicket :many
SELECT t.opid, t.tid, t.updated_at, t.op, t.new_status, t.new_priority, t.new_appointment, t.new_category, t.remark, o.name
FROM wts.ticket_traces t
LEFT JOIN wts.v_operators o ON o.wid = t.op
WHERE t.tid = $1
ORDER BY t.updated_at DESC
`

type ListTracesByTicketRow struct {
	Opid           int32              `json:"opid"`
	Tid            int32              `json:"tid"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	Op             string             `json:"op"`
	NewStatus      NullWtsStatus      `json:"new_status"`
	NewPriority    NullWtsPriority    `json:"new_priority"`
	NewAppointment pgtype.Date        `json:"new_appointment"`
	NewCategory    NullWtsCategory    `json:"new_category"`
	Remark         string             `json:"remark"`
	Name           pgtype.Text        `json:"name"`
}

func (q *Queries) ListTracesByTicket(ctx context.Context, tid int32) ([]ListTracesByTicketRow, error) {
	rows, err := q.db.Query(ctx, listTracesByTicket, tid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTracesByTicketRow
	for rows.Next() {
		var i ListTracesByTicketRow
		if err := rows.Scan(
			&i.Opid,
			&i.Tid,
			&i.UpdatedAt,
			&i.Op,
			&i.NewStatus,
			&i.NewPriority,
			&i.NewAppointment,
			&i.NewCategory,
			&i.Remark,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :one
UPDATE wts.users
SET 
  phone = $2,
  block = $3,
  room = $4,
  isp = $5,
  account = $6
WHERE sid = $1
RETURNING sid, phone, block, room, isp, account, wx, op, registered_at, updated_at
`

type UpdateUserParams struct {
	Sid     string       `json:"sid"`
	Phone   pgtype.Text  `json:"phone"`
	Block   NullWtsBlock `json:"block"`
	Room    pgtype.Text  `json:"room"`
	Isp     NullWtsIsp   `json:"isp"`
	Account pgtype.Text  `json:"account"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (WtsUser, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.Sid,
		arg.Phone,
		arg.Block,
		arg.Room,
		arg.Isp,
		arg.Account,
	)
	var i WtsUser
	err := row.Scan(
		&i.Sid,
		&i.Phone,
		&i.Block,
		&i.Room,
		&i.Isp,
		&i.Account,
		&i.Wx,
		&i.Op,
		&i.RegisteredAt,
		&i.UpdatedAt,
	)
	return i, err
}
